# A Terraform module to create a subset of cloud components
# Copyright (C) 2022 Skaylink GmbH

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# For questions and contributions please contact info@iq3cloud.com

locals {
  grafana_name       = "${var.name}-grafana"
  log_analytics_name = "${var.name}-log-analytics"
}

resource "azurerm_resource_group_template_deployment" "grafana" {
  name                = "grafana"
  resource_group_name = data.azurerm_resource_group.rg.name
  deployment_mode     = "Incremental"
  template_content    = <<TEMPLATE
  {
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "resources": [
      {
      "type": "Microsoft.Dashboard/grafana",
      "apiVersion": "2021-09-01-preview",
      "name": "${local.grafana_name}",
      "location": "${data.azurerm_resource_group.rg.location}",
      "sku": {
          "name": "Standard"
      },
      "identity": {
          "type": "SystemAssigned"
        },
      "properties": {
          "autoGeneratedDomainNameLabelScope": "TenantReuse",
          "zoneRedundancy": "Disabled"
        }
      }
    ]
  }
  TEMPLATE
}

resource "azurerm_log_analytics_workspace" "workspace" {
  count = var.log_analytics_workspace == true ? 1 : 0

  name                = local.log_analytics_name
  location            = data.azurerm_resource_group.rg.location
  resource_group_name = data.azurerm_resource_group.rg.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

provider "azurerm" {
  features {}
}

resource "azurerm_role_assignment" "grafana_admin" {

  scope                = data.azurerm_resource_group.rg.id
  role_definition_name = "Grafana Admin"
  principal_id         = var.admin_user_object_id
}
